### ISSUE TITLE
crash when querying video formats

### ISSUE THREAD

**Issue by ZacDiggum** [morefigs/py-ic-imaging-control#13]
Hi,
I'm using pyicic on Windows 7 x64 with Python 3.5 x64 and tisgrabber_x64.dll. The camera is a DMM 24UP031-ML. This line in the example script crashes Python most of the time (but not always) without any error message:
`formats = cam.list_video_formats()`
The only thing I get is the Windows error message.
Any idea what might be the problem?

**Comment by morefigs** [comment]
If you follow the definition of `list_video_formats` you'll see that a fixed size (80 x 40) char array is being created and passed to the underlying function. If this array if the wrong size and/or the data being written doesn't fit in the array you may well get a crash. I don't have a camera at this stage so all I can suggest is playing with this size or investigating if there is a recommended size you can use instead.

**Comment by ZacDiggum** [comment]
Thanks for the hint. I'll play around with the char array a little. Maybe I can come up with a fix.

**Comment by morefigs** [comment]
The example in tisgrabber.h does use the same size array, but yes, still experiment with it.

**Comment by adrian-pps** [comment]
I ran into the same problem as ZacDiggum, and followed the advice of morefigs,
and found some potential solutions.
I'm using a DMK 27BUP031 camera that has 66(!) formats in the list. The changes listed
next have been tested with Python 3.5, 64-bit and Python 2.7, 32-bit.

Fix, option 1.
-------------
Replace the function list_video_formats in IC_Camera.py with this version:

    def list_video_formats(self):
        """
        :returns: list -- available video formats.
        """
        return [self.get_video_format(idx) for idx in range(self.get_video_format_count())]

This is the simplest solution, and sidesteps the problem of the fixed size allocation in
the character buffer. In fact, this option is mentioned in the C header file tisgrabber.h
at line 679, "Simpler approach of enumerating video formats. No 2D char array needed."
Using a list comprehension is also more "Pythonic", and avoids more ctypes manipulations.


Fix, option 2.
-------------
This option is to actually fix the buffer problem. The issue appears to be that the
use of hard-coded 80 and 40 are reversed from what is required.

Replace line 655 in IC_GrabberDLL.py with:
                                   POINTER((c_char * 40) * 80),

In function list_video_formats(), in IC_Camera.py:
A. Replace the assignment to vf_list with:
            vf_list = ((c_char * 40) * 80)()
B. The last parameter in the call to IC_GrabberDLL.list_video_formats should be 40, not 80:
                                                       c_int(40))

As I understand it, with these changes, each format can now be up to 39 characters
(one less than 40), and there can be up to 80 formats in the list.

Of course, this is only a partial fix, because the number of formats that can be handled
is now hard-coded at 80, and some future (or present) camera may exceed this number of
formats.

I have tested this on only the one camera mentioned earlier.

**Comment by morefigs** [comment]
Fix option 1 sounds like the way to go. If someone makes a pull request for that I can add it, or I can do it myself in the nearish future.

**Comment by adrian-pps** [comment]
This issue is resolved and should be closed.

**Comment by ZacDiggum** [comment]
Thank you @adrian-pps  and @morefigs!

**Comment by deshpandegaurang** [comment]
Thank you

On 22-Nov-2017 4:53 PM, "ZacDiggum" <notifications@github.com> wrote:

Thank you @adrian-pps <https://github.com/adrian-pps> and @morefigs
<https://github.com/morefigs>!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/morefigs/py-ic-imaging-control/issues/13#issuecomment-346322246>,
or mute the thread
