### ISSUE TITLE
frequent errors when setting property values

### ISSUE THREAD

**Issue by ZacDiggum** [morefigs/py-ic-imaging-control#17]
Hi,
when setting property values like exposure time or gain I get frequent crashes:
```
Traceback (most recent call last):
  File "pyicic_test.py", line 10, in <module>
    cam.exposure.value = int(np.rint(10000 / 60))
  File "C:\winpython\python\lib\site-packages\pyicic\IC_Property.py", line 81, i
n value
    if self.auto_available:
  File "C:\winpython\python\lib\site-packages\pyicic\IC_Property.py", line 29, i
n auto_available
    c_int(self._prop_index))
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type
```
The test script is simply:
```
from pyicic.IC_ImagingControl import *
import numpy as np

ic_ic = IC_ImagingControl()
ic_ic.init_library()
cam = ic_ic.get_device(ic_ic.get_unique_device_names()[0])
cam.open()
cam.exposure.value = int(np.rint(10000 / 60))
cam.close()
ic_ic.close_library()
```
The errors occur every third or fourth time I execute the script.

Unrelated question: how do I turn off auto whitebalance?
cam.whitebalance.auto = False or 0 gives IC_Exception 0.
Thanks in advance...

**Comment by morefigs** [comment]
Strange, I can't immediately see why that's happening.

On a side note, you're getting random errors but you're also passing a random number, so try passing a consistent value into the function and see if you still get random errors. You can also check the range with `cam.exposure.range`.

**Comment by ZacDiggum** [comment]
`np.rint()` rounds to the nearest integer, it's not `np.randint()`. The line sets the exposure time to 1/60 s.
Hm, and how would I turn off auto whitebalance and set values? Or more general, how can I find out valid property values for properties that don't have .min, .max, .range and .value? Is there a way of getting the 'structure' of a property?
Thanks for your patience... :-)

**Comment by morefigs** [comment]
Ah, my bad :)

There are DLL functions `IC_SetWhiteBalanceAuto`, `IC_SetWhiteBalanceRed` (etc) that aren't implemented. You can view them in `IC_GrabberDLL.py`. Feel free to implement those in a PR, or I can do it soonish. They may be what you need. I can't say I know what the difference between this function and the video property white balance is.

Note that the `enable_trigger` function always gets an error returned, yet still works. It's possible this is the case with your `IC_Exception` you're seeing as well. Does it actually seem to fail?

I'm not sure it's possible to find a property's range (etc) if the `range` method doesn't work (it's been a while since I've used these cameras).

**Comment by ZacDiggum** [comment]
I'll try my best with implementing the functions. For now I'm using the property dialog.
The IC_Exceptions I mentioned actually crash the program (setting exposure and gain mainly).
Anyway, thank you for help...
